# 4.3.2 데이터세트 및
# 4.3.4 파이선 연관 분석

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Book2/Ch4/basket_analysis.csv')
df.shape

(999, 17)

In [ ]:
df.head(3)

,Unnamed: 0,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True

In [ ]:
# Unnamed: 0 컬럼 제거
df = df.drop('Unnamed: 0',axis=1)
df.head(3)

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True

In [ ]:
df1 = df.replace(True, 1).replace(False, "")   # True를 1로, False를 결측값으로 변환
df1.head(3)

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,,1,,,1,1,,1,,,,,1,,1,1
1,,,,,,,,,,1,,,,,,
2,1,,1,,,1,,1,,1,,,,,1,1

In [ ]:
# 데이터프레임 df1를 구글 클라우드 지정 경로에 basket_analysis_number.csv 파일명으로 저장
df1.to_csv('/content/drive/MyDrive/Colab Notebooks/Book2/Ch4/basket_analysis_number.csv', index=False)

In [ ]:
df.head(3)

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True

In [ ]:
# mlxtend 라이브러리에서 apriori, association_rules 기능 import 
from mlxtend.frequent_patterns import apriori, association_rules
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Apriori 알고리듬을 통해 Frequent Itemsets 계산
# 오렌지3 Frequent Itemsets 환경설정과 동일하게 설정
frequent_itemsets = apriori(df,
                            min_support = .01,
                            max_len = 6,
                            use_colnames = True)

In [ ]:
# Frequent Itemset를 support값에 따라 sort 후 첫 5행까지 디스플레이
frequent_itemsets.sort_values(by=['support']).head()

      support                                           itemsets
9415  0.01001  (Unicorn, Kidney Beans, Bread, Sugar, Corn, Eggs)
7924  0.01001       (Cheese, Unicorn, Apple, Dill, Nutmeg, Eggs)
7930  0.01001         (Yogurt, Cheese, Apple, Dill, Sugar, Eggs)
7934  0.01001  (Cheese, Milk, Apple, Kidney Beans, Dill, Ice ...
7936  0.01001  (Cheese, Apple, Kidney Beans, Dill, Ice cream,...

In [ ]:
# Frequent_Itemsets를 대상으로 연관 규칙(Association rule) 생성 
rules = association_rules(frequent_itemsets,
                            metric = 'support',
                            min_threshold=0.01)

In [ ]:
rules.shape

(473170, 9)

In [ ]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Bread),(Apple),0.384384,0.383383,0.154154,0.401042,1.046059,0.006788,1.029482
1,(Apple),(Bread),0.383383,0.384384,0.154154,0.402089,1.046059,0.006788,1.029610
2,(Butter),(Apple),0.420420,0.383383,0.188188,0.447619,1.167549,0.027006,1.116289
3,(Apple),(Butter),0.383383,0.420420,0.188188,0.490862,1.167549,0.027006,1.138354
4,(Cheese),(Apple),0.404404,0.383383,0.162162,0.400990,1.045925,0.007120,1.029393
...,...,...,...,...,...,...,...,...,...
473165,(Unicorn),"(Yogurt, Nutmeg, Sugar, Onion, chocolate)",0.389389,0.023023,0.012012,0.030848,1.339890,0.003047,1.008074
473166,(Nutmeg),"(Yogurt, Unicorn, Sugar, Onion, chocolate)",0.401401,0.026026,0.012012,0.029925,1.149818,0.001565,1.004019
473167,(Sugar),"(Yogurt, Unicorn, Nutmeg, Onion, chocolate)",0.409409,0.026026,0.012012,0.029340,1.127327,0.001357,1.003414
473168,(Onion),"(Yogurt, Unicorn, Nutmeg, Sugar, chocolate)",0.403403,0.022022,0.012012,0.029777,1.352132,0.003128,1.007993
473169,(chocolate),"(Yogurt, Unicorn, Nutmeg, Sugar, Onion)",0.421421,0.022022,0.012012,0.028504,1.294321,0.002731,1.006672

In [ ]:
c1 = rules['confidence'] > 0.85   # 조건 C1 생성
filtered_rules = rules[c1]        # 조건 C1을 만족하는 연관 규칙 필터링
filtered_rules.shape

(36, 9)

In [ ]:
# support 변수 기준으로 내림차순 정렬
filtered_rules.sort_values(by=['support'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
287050,"(Milk, Bread, Butter, Nutmeg, Corn)",(Kidney Beans),0.024024,0.408408,0.021021,0.875000,2.142463,0.011209,4.732733
321211,"(Milk, Unicorn, Bread, Nutmeg, Corn)",(Kidney Beans),0.021021,0.408408,0.019019,0.904762,2.215336,0.010434,6.211712
249164,"(Unicorn, Apple, Ice cream, Nutmeg, Sugar)",(Corn),0.022022,0.407407,0.019019,0.863636,2.119835,0.010047,4.345679
246871,"(Unicorn, Apple, Nutmeg, Sugar, Eggs)",(Corn),0.021021,0.407407,0.018018,0.857143,2.103896,0.009454,4.148148
223124,"(Cheese, Unicorn, Apple, Nutmeg, Sugar)",(Corn),0.021021,0.407407,0.018018,0.857143,2.103896,0.009454,4.148148
287174,"(Milk, Bread, Butter, Sugar, Corn)",(Kidney Beans),0.021021,0.408408,0.018018,0.857143,2.098739,0.009433,4.141141
253815,"(Unicorn, Apple, Nutmeg, Sugar, chocolate)",(Corn),0.021021,0.407407,0.018018,0.857143,2.103896,0.009454,4.148148
321150,"(Milk, Bread, Nutmeg, Sugar, Corn)",(Kidney Beans),0.021021,0.408408,0.018018,0.857143,2.098739,0.009433,4.141141
219715,"(Cheese, Unicorn, Apple, Sugar, Eggs)",(Corn),0.021021,0.407407,0.018018,0.857143,2.103896,0.009454,4.148148
367464,"(Milk, Butter, Ice cream, Nutmeg, Corn)",(Kidney Beans),0.021021,0.408408,0.018018,0.857143,2.098739,0.009433,4.141141
318980,"(Milk, Bread, Ice cream, Nutmeg, Corn)",(Kidney Beans),0.019019,0.408408,0.017017,0.894737,2.190789,0.009249,5.620120
411669,"(Eggs, Cheese, Dill, Sugar, chocolate)",(Kidney Beans),0.020020,0.408408,0.017017,0.850000,2.081250,0.008841,3.943944
287112,"(Milk, Bread, Butter, Onion, Corn)",(Kidney Beans),0.020020,0.408408,0.017017,0.850000,2.081250,0.008841,3.943944
337519,"(Kidney Beans, Bread, Sugar, Onion, chocolate)",(Yogurt),0.018018,0.420420,0.016016,0.888889,2.114286,0.008441,5.216216
423758,"(Cheese, chocolate, Unicorn, Sugar, Eggs)",(Kidney Beans),0.018018,0.408408,0.016016,0.888889,2.176471,0.008657,5.324324
456372,"(Yogurt, chocolate, Unicorn, Dill, Eggs)",(Milk),0.018018,0.405405,0.016016,0.888889,2.192593,0.008711,5.351351
172595,"(Unicorn, Apple, Bread, Sugar, Eggs)",(Corn),0.017017,0.407407,0.015015,0.882353,2.165775,0.008082,5.037037
331006,"(Bread, Ice cream, Nutmeg, Onion, Eggs)",(Sugar),0.016016,0.409409,0.014014,0.875000,2.137225,0.007457,4.724725
312407,"(Cheese, Unicorn, Bread, Nutmeg, Sugar)",(Kidney Beans),0.016016,0.408408,0.014014,0.875000,2.142463,0.007473,4.732733
168502,"(Cheese, Unicorn, Apple, Bread, Sugar)",(Corn),0.016016,0.407407,0.014014,0.875000,2.147727,0.007489,4.740741
301619,"(Cheese, Unicorn, Bread, Nutmeg, Corn)",(Kidney Beans),0.014014,0.408408,0.013013,0.928571,2.273634,0.007290,8.282282
440687,"(Corn, Kidney Beans, Ice cream, Onion, Eggs)",(Yogurt),0.015015,0.420420,0.013013,0.866667,2.061429,0.006700,4.346847
168317,"(Cheese, Apple, Bread, Nutmeg, Corn)",(Sugar),0.015015,0.409409,0.013013,0.866667,2.116870,0.006866,4.429429
421217,"(Eggs, Cheese, Ice cream, Sugar, chocolate)",(Kidney Beans),0.015015,0.408408,0.013013,0.866667,2.122059,0.006881,4.436937
413094,"(Cheese, chocolate, Unicorn, Nutmeg, Eggs)",(Dill),0.014014,0.398398,0.013013,0.928571,2.330761,0.007430,8.422422
167635,"(Cheese, Unicorn, Apple, Bread, Eggs)",(Corn),0.014014,0.407407,0.013013,0.928571,2.279221,0.007304,8.296296
316001,"(Yogurt, Unicorn, Dill, Bread, Corn)",(Sugar),0.014014,0.409409,0.012012,0.857143,2.093608,0.006275,4.134134
440062,"(Yogurt, Unicorn, Dill, Nutmeg, Corn)",(chocolate),0.014014,0.421421,0.012012,0.857143,2.033933,0.006106,4.050050
381100,"(Milk, Unicorn, Dill, Butter, Sugar)",(chocolate),0.014014,0.421421,0.012012,0.857143,2.033933,0.006106,4.050050
393629,"(Unicorn, Dill, Nutmeg, Corn, Eggs)",(Cheese),0.014014,0.404404,0.012012,0.857143,2.119519,0.006345,4.169169
180721,"(Apple, Kidney Beans, Bread, Onion, Eggs)",(Yogurt),0.014014,0.420420,0.012012,0.857143,2.038776,0.006120,4.057057
325553,"(Eggs, Dill, Bread, Ice cream, chocolate)",(Yogurt),0.014014,0.420420,0.012012,0.857143,2.038776,0.006120,4.057057
264359,"(Apple, Kidney Beans, Ice cream, Onion, Eggs)",(Milk),0.014014,0.405405,0.012012,0.857143,2.114286,0.006331,4.162162
161187,"(Unicorn, Apple, Bread, Butter, Eggs)",(Corn),0.014014,0.407407,0.012012,0.857143,2.103896,0.006303,4.148148
254807,"(Apple, Dill, Ice cream, Nutmeg, Eggs)",(Sugar),0.012012,0.409409,0.011011,0.916667,2.238998,0.006093,7.087087
172285,"(Unicorn, Apple, Bread, Nutmeg, Eggs)",(Corn),0.011011,0.407407,0.010010,0.909091,2.231405,0.005524,6.518519